### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by howard-206** [JoeJoeTV/AstroTuxLauncher#12]
The update feature seems to be not working. I waited for a long time, but nothing happened. 
After troubleshooting, I manually downloaded the latest version of DepotDownloader and placed it in the libs folder. Once I did that, the update worked as expected.

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the update_server method to ensure DepotDownloader is downloaded and up-to-date before using it. Added a new method check_depotdownloader to handle this process.

You can review changes in this commit: https://github.com/lattaai13/JoeJoeTV-AstroTuxLauncher-12/commit/a65365845788481d84d1323016d03d066fc27291.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by JoeJoeTV** [comment]
> The update feature seems to be not working. I waited for a long time, but nothing happened. 
> After troubleshooting, I manually downloaded the latest version of DepotDownloader and placed it in the libs folder. Once I did that, the update worked as expected.
> 

If it worked afterwards, the DepotDownloader file might have been corrupt or the veraion too old.
I have not yet implemented an update machanism for DeptotDownloader, so if it didn't work because it was too old, then this is currently expected.
In the rewrite I am doing, I will try to solve thia problem.

You can still send me the log file, maybe it will help.

**Comment by JoeJoeTV** [comment]
@howard-206 I have confirmed that this issue is very likely related to an old version of DepotDownloader being used, as I have observed the same issue with my own server instance.
Again, this is currently expected, as DepotDownloader is not automatically updated.
The official "fix", is to just delete the "libs" folder and let DepotDownlaoder be downloaded automatically again.

**Comment by howard-206** [comment]
I understand the issue now. Deleting the libs folder and letting it automatically download again is also a convenient solution.
Thanks for your response and for looking into this.
